### ISSUE TITLE
Add Android 13 support.

### ISSUE THREAD

**Issue by roipeker** [roipeker/flutter_translation_sheet#23]
As Android 13 now behaves similar to iOS with per-app language preferences, maybe makes sense to generate [locales_config.xml](https://developer.android.com/guide/topics/resources/app-languages#app-language-settings)
and see if we add a common interfase to iOS/Android (native code) to retrieve and assign the selected locale from app's Settings.

**Comment by IsmailAlamKhan** [comment]
Shouldn't this be closed as its already implemented? @roipeker
