### ISSUE TITLE
Does not work with Dart 3.1.0

### ISSUE THREAD

**Issue by fotiDim** [roipeker/flutter_translation_sheet#29]
I updated to latest flutter and when doing `fts run` I am getting:

Can't load Kernel binary: Invalid kernel binary format version.
flutter_translation_sheet 1.0.27 doesn't support Dart 3.1.0.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-arm64, locale
    en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Comment by PhilipChng** [comment]
👋🏼 Hi @roipeker , not sure if you missed a notification on this package again 🙈

**Comment by roipeker** [comment]
Yep, indeed

**Comment by roipeker** [comment]
Sadly, couldn't workaround the exceptions on posix brought by the dcli dependency during the upgrade. It's odd but works fine locally, yet I bumped 3 trial versions so far on pubdev testing for that issue. Sadly, don't have much time available, if anyone finds a fix for the dependency issues, please make a PR and i will be happy to merge it.
On the bright side, [this comment](https://github.com/onepub-dev/dcli/issues/221#issuecomment-1689585292) might help to get the latest version working.

Sorry guys.

**Comment by fotiDim** [comment]
@roipeker I have managed to work around the issue locally by adding those overrides:

```yaml
dependency_overrides:
  file: ^7.0.0
  pubspec2: ^3.0.0
  collection: ^1.18.0
```

It seems that `dcli` should release a new version and you should downgrade collection to `collection: ^1.17.2`.

**Comment by roipeker** [comment]
Yeah, thats what I changed in the latest version, works when u deploy locally, but fails with the global pub install sadly.

**Comment by fotiDim** [comment]
Opened an [issue](https://github.com/onepub-dev/dcli/issues/222) in dcli.

**Comment by roipeker** [comment]
Thanks @fotiDim , the maintainers were notified by comment on the original response as well, so let's hope they fix it soon.

**Comment by roipeker** [comment]
Thanks @fotiDim , the maintainers were notified by comment on the original response as well, so let's hope they fix it soon.

**Comment by fotiDim** [comment]
@roipeker I think this can be closed now. With the latest Flutter and dcli updates the issue is gone.

**Comment by dv30fps** [comment]
fts 1.0.32 works for me on Flutter 3.13.1. However, when I run fts as a command in a terminal, I see, "Can't load Kernel binary: Invalid kernel binary format version." I deleted the cache in the bin of the Flutter directory. The message continues to print, but it appears to have no negative impact on fts running.
